#server config
server:
  port: ${TRUSTORACLE_SERVICE_PORT:5021}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_IP:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:trustoracle}?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ${MYSQL_USER:trustoracle}
    password: ${MYSQL_PASSWORD:defaultPassword}
  jpa:
    generate-ddl: true
